export var exercises = [
    { name: 'Bar Dip' },
    { name: 'Bench Press' },
    { name: 'Cable Chest Press' },
    { name: 'Close-Grip Bench Press' },        
    { name: 'Close-Grip Feet-Up Bench Press' },
    { name: 'Decline Bench Press' },
    { name: 'Dumbbell Chest Fly' },
    { name: 'Dumbbell Chest Press' },
    { name: 'Dumbbell Floor Press' },
    { name: 'Dumbbell Pullover' },
    { name: 'Feet-Up Bench Press' },
    { name: 'Floor Press' },
    { name: 'Incline Bench Press' },
    { name: 'Incline Dumbbell Press' },        
    { name: 'Incline Push-Up' },
    { name: 'Kneeling Incline Push-Up' },      
    { name: 'Kneeling Push-Up' },
    { name: 'Machine Chest Fly' },
    { name: 'Machine Chest Press' },
    { name: 'Pec Deck' },
    { name: 'Push-Up' },
    { name: 'Push-Up Against Wall' },
    { name: 'Resistance Band Chest Fly' },
    { name: 'Smith Machine Bench Press' },
    { name: 'Smith Machine Incline Bench Press' },
    { name: 'Standing Cable Chest Fly' },
    { name: 'Band External Shoulder Rotation' },
    { name: 'Band Internal Shoulder Rotation' },
    { name: 'Band Pull-Apart' },
    { name: 'Barbell Front Raise' },
    { name: 'Barbell Rear Delt Row' },
    { name: 'Barbell Upright Row' },
    { name: 'Behind the Neck Press' },
    { name: 'Cable Lateral Raise' },
    { name: 'Cable Rear Delt Row' },
    { name: 'Dumbbell Front Raise' },
    { name: 'Dumbbell Horizontal Internal Shoulder Rotation' },
    { name: 'Dumbbell Horizontal External Shoulder Rotation' },
    { name: 'Dumbbell Lateral Raise' },
    { name: 'Dumbbell Rear Delt Row' },
    { name: 'Dumbbell Shoulder Press' },
    { name: 'Face Pull' },
    { name: 'Lying Dumbbell External Shoulder Rotation' },
    { name: 'Lying Dumbbell Internal Shoulder Rotation' },
    { name: 'Machine Lateral Raise' },
    { name: 'Machine Shoulder Press' },
    { name: 'Monkey Row' },
    { name: 'Overhead Press' },
    { name: 'Power Jerk' },
    { name: 'Push Press' },
    { name: 'Reverse Dumbbell Flyes' },
    { name: 'Reverse Machine Fly' },
    { name: 'Seated Dumbbell Shoulder Press' },
    { name: 'Seated Barbell Overhead Press' },
    { name: 'Seated Smith Machine Shoulder Press' },
    { name: 'Snatch Grip Behind the Neck Press' },
    { name: 'Squat Jerk' },
    { name: 'Split Jerk' },
    { name: 'Barbell Curl' },
    { name: 'Barbell Preacher Curl' },
    { name: 'Cable Curl With Bar' },
    { name: 'Cable Curl With Rope' },
    { name: 'Concentration Curl' },
    { name: 'Dumbbell Curl' },
    { name: 'Dumbbell Preacher Curl' },
    { name: 'Hammer Curl' },
    { name: 'Incline Dumbbell Curl' },
    { name: 'Spider Curl' },
    { name: 'Barbell Standing Triceps Extension' },
    { name: 'Barbell Lying Triceps Extension' },
    { name: 'Bench Dip' },
    { name: 'Close-Grip Push-Up' },
    { name: 'Dumbbell Lying Triceps Extension' },
    { name: 'Dumbbell Standing Triceps Extension' },
    { name: 'Overhead Cable Triceps Extension' },
    { name: 'Tricep Pushdown With Bar' },
    { name: 'Tricep Pushdown With Rope' },
    { name: 'Air Squat' },
    { name: 'Barbell Hack Squat' },
    { name: 'Barbell Lunge' },
    { name: 'Body Weight Lunge' },
    { name: 'Box Squat' },
    { name: 'Bulgarian Split Squat' },
    { name: 'Chair Squat' },
    { name: 'Dumbbell Lunge' },
    { name: 'Dumbbell Squat' },
    { name: 'Front Squat' },
    { name: 'Goblet Squat' },
    { name: 'Hack Squat Machine' },
    { name: 'Half Air Squat' },
    { name: 'Hip Adduction Machine' },
    { name: 'Landmine Hack Squat' },
    { name: 'Landmine Squat' },
    { name: 'Leg Extension' },
    { name: 'Leg Press' },
    { name: 'Lying Leg Curl' },
    { name: 'Pause Squat' },
    { name: 'Safety Bar Squat' },
    { name: 'Seated Leg Curl' },
    { name: 'Shallow Body Weight Lunge' },
    { name: 'Side Lunges (Bodyweight)' },
    { name: 'Smith Machine Squat' },
    { name: 'Squat' },
    { name: 'Step Up' },
    { name: 'Back Extension' },
    { name: 'Barbell Row' },
    { name: 'Barbell Shrug' },
    { name: 'Block Snatch' },
    { name: 'Cable Close Grip Seated Row' },
    { name: 'Cable Wide Grip Seated Row' },
    { name: 'Chin-Up' },
    { name: 'Clean' },
    { name: 'Clean and Jerk' },
    { name: 'Deadlift' },
    { name: 'Deficit Deadlift' },
    { name: 'Dumbbell Deadlift' },
    { name: 'Dumbbell Romanian Deadlift' },
    { name: 'Dumbbell Row' },
    { name: 'Dumbbell Shrug' },
    { name: 'Floor Back Extension' },
    { name: 'Good Morning' },
    { name: 'Hang Clean' },
    { name: 'Hang Power Clean' },
    { name: 'Hang Power Snatch' },
    { name: 'Hang Snatch' },
    { name: 'Inverted Row' },
    { name: 'Inverted Row with Underhand Grip' },
    { name: 'Kettlebell Swing' },
    { name: 'Lat Pulldown With Pronated Grip' },
    { name: 'Lat Pulldown With Supinated Grip' },
    { name: 'One-Handed Cable Row' },
    { name: 'One-Handed Lat Pulldown' },
    { name: 'Pause Deadlift' },
    { name: 'Pendlay Row' },
    { name: 'Power Clean' },
    { name: 'Power Snatch' },
    { name: 'Pull-Up' },
    { name: 'Rack Pull' },
    { name: 'Romanian Deadlift' },
    { name: 'Seal Row' },
    { name: 'Seated Machine Row' },
    { name: 'Snatch' },
    { name: 'Snatch Grip Deadlift' },
    { name: 'Stiff-Legged Deadlift' },
    { name: 'Straight Arm Lat Pulldown' },
    { name: 'Sumo Deadlift' },
    { name: 'T-Bar Row' },
    { name: 'Trap Bar Deadlift With High Handles' },
    { name: 'Trap Bar Deadlift With Low Handles' },
    { name: 'Banded Side Kicks' },
    { name: 'Cable Pull Through' },
    { name: 'Clamshells' },
    { name: 'Fire Hydrants' },
    { name: 'Glute Bridge' },
    { name: 'Hip Abduction Against Band' },
    { name: 'Hip Abduction Machine' },
    { name: 'Hip Thrust' },
    { name: 'Hip Thrust Machine' },
    { name: 'Hip Thrust With Band Around Knees' },
    { name: 'Lateral Walk With Band' },
    { name: 'One-Legged Glute Bridge' },
    { name: 'One-Legged Hip Thrust' },
    { name: 'Step Up' },
    { name: 'Cable Crunch' },
    { name: 'Crunch' },
    { name: 'Hanging Leg Raise' },
    { name: 'Hanging Knee Raise' },
    { name: 'Hanging Sit-Up' },
    { name: 'High to Low Wood Chop with Band' },
    { name: 'Horizontal Wood Chop with Band' },
    { name: 'Kneeling Ab Wheel Roll-Out' },
    { name: 'Kneeling Plank' },
    { name: 'Kneeling Side Plank' },
    { name: 'Lying Leg Raise' },
    { name: 'Lying Windshield Wiper' },
    { name: 'Lying Windshield Wiper with Bent Knees' },
    { name: 'Machine Crunch' },
    { name: 'Oblique Crunch' },
    { name: 'Oblique Sit-Up' },
    { name: 'Plank' },
    { name: 'Side Plank' },
    { name: 'Sit-Up' },
    { name: 'Eccentric Heel Drop' },
    { name: 'Heel Raise' },
    { name: 'Seated Calf Raise' },
    { name: 'Standing Calf Raise' },
    { name: 'Barbell Wrist Curl' },
    { name: 'Barbell Wrist Curl Behind the Back' },
    { name: 'Bar Hang' },
    { name: 'Dumbbell Wrist Curl' },
    { name: 'Farmers Walk' },
    { name: 'Fat Bar Deadlift' },
    { name: 'Gripper' },
    { name: 'One-Handed Bar Hang' },
    { name: 'Plate Pinch' },
    { name: 'Plate Wrist Curl' },
    { name: 'Towel Pull-Up' },
    { name: 'Barbell Wrist Extension' },
    { name: 'Dumbbell Wrist Extension' },
]

exercises = exercises.sort((a, b) =>
    a.name.localeCompare(b.name));